Some refactoring.

diff --git a/minifetch b/minifetch
--- a/minifetch
+++ b/minifetch
@@ -1,28 +1,46 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# This small script is under the GPLv3 license.
+
+# It is intender to use in debian systems
+# other distros are not supported.
+
+set -o errexit   # exit on error
 
 # colors
-color1="\033[0;35m" # titles
-color2="\033[0;31m" # ascii logo
-color3="\033[1;32m" # info
-reset="\033[0m"     # reset coloring
+function minifetch_set_colors ()
+{
+    title_color="\e[1;34m" # titles
+    ascii_color="\e[1;31m" # ascii logo
+    info_color="\e[0;32m"  # info
+    reset_colors="\e[0m"   # reset_colors coloring
+}
 
+function minifetch_get_system_info ()
+{
+    debian_version="debian $(cat /etc/debian_version)"
+    sysarch="$HOSTTYPE"
+    desktop=$(echo $XDG_CURRENT_DESKTOP | awk '{print tolower($0)}')
+    shell="$(basename $SHELL)"
+    packages="$(dpkg -l | grep -c ^i)"
+    kernel="$(uname -rs | awk '{print tolower($0)}')"
+    uptime="$(uptime -p | sed "s/up //")"
+}
 
-# system information
-os="$(sed "s/.*=\"//g" /etc/os-release | sed "s/\"//g" | head --lines=1 | awk '{print tolower($0)}')"
-sysarch="$HOSTTYPE"
-wm=$(wmctrl -m | grep Name | awk -F: '{print tolower($2)}' | xargs)
-shell="$(basename $SHELL)"
-packages="$(dpkg -l | grep -c ^i)"
-kernel="$(uname -r | sed "s/-.*//g")"
-uptime="$(uptime -p | sed "s/up //")"
+function minifetch_print_information ()
+{
+    printf "+---------------+\n"
+    printf "|${ascii_color}    .ooooo+.   ${reset_colors}|  ${title_color}os:       ${info_color}${debian_version}${reset_colors}\n"
+    printf "|${ascii_color}  .oo+....o=+  ${reset_colors}|  ${title_color}kernel:   ${info_color}${kernel}${reset_colors}\n"
+    printf "|${ascii_color}  o+  ...  oo  ${reset_colors}|  ${title_color}desktop:  ${info_color}${desktop}${reset_colors}\n"
+    printf "|${ascii_color}  =   +.  .+.  ${reset_colors}|  ${title_color}shell:    ${info_color}${shell}${reset_colors}\n"
+    printf "|${ascii_color}  oo   ....    ${reset_colors}|  ${title_color}packages: ${info_color}${packages}${reset_colors}\n"
+    printf "|${ascii_color}   ++.         ${reset_colors}|  ${title_color}sysarch:  ${info_color}${sysarch}${reset_colors}\n"
+    printf "|${ascii_color}    .+.        ${reset_colors}|  ${title_color}uptime:   ${info_color}${uptime}${reset_colors}\n"
+    printf "+---------------+\n"
+}
 
-# output
-printf "+---------------+\n"
-printf "|${color2}    .ooooo+.   ${reset}|  ${color1}os:       ${color3}${os}${reset}\n"
-printf "|${color2}  .oo+....o=+  ${reset}|  ${color1}kernel:   ${color3}version ${kernel}${reset}\n"
-printf "|${color2}  o+  ...  oo  ${reset}|  ${color1}wm:       ${color3}${wm}${reset}\n"
-printf "|${color2}  =   +.  .+.  ${reset}|  ${color1}shell:    ${color3}${shell}${reset}\n"
-printf "|${color2}  oo   ....    ${reset}|  ${color1}packages: ${color3}${packages}${reset}\n"
-printf "|${color2}   ++.         ${reset}|  ${color1}sysarch:  ${color3}${sysarch}${reset}\n"
-printf "|${color2}    .+.        ${reset}|  ${color1}uptime:   ${color3}${uptime}${reset}\n"
-printf "+---------------+\n"
+# run the stuff
+minifetch_set_colors
+minifetch_get_system_info
+minifetch_print_information
